http:
  routers:
    whoami-router:
      rule: "Host(`whoami.localhost`)"
      service: whoami-service

  services:
    whoami-service:
      loadBalancer:
        servers:
          - url: "http://whoami:80"
